<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0uj0Mp9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0uj0Mp9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container0uj0Mp9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container0uj0Mp9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container0uj0Mp9\App_KernelDevDebugContainer([
    'container.build_hash' => '0uj0Mp9',
    'container.build_id' => 'd4be0edb',
    'container.build_time' => 1593634531,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0uj0Mp9');
