<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'events' => [[], ['_controller' => 'App\\Controller\\EventsController::view'], [], [['text', '/events']], [], []],
    'events_index' => [[], ['_controller' => 'App\\Controller\\EventsController::index'], [], [['text', '/events']], [], []],
    'events_add' => [[], ['_controller' => 'App\\Controller\\EventsController::add'], [], [['text', '/events']], [], []],
    'events_get' => [[], ['_controller' => 'App\\Controller\\EventsController::view'], [], [['text', '/events']], [], []],
];
